- name: deploy public ssh key
  authorized_key:
    user: root
    key: "{{item}}"
  with_items:
    - "{{ssh_authorized_key.jtrijean}}"
    - "{{ssh_authorized_key.root}}"

- name: script dump mongo
  template:
    src: dumpMongo.sh
    dest: /usr/local/bin/dumpMongo.sh

- name: start cron daily dump
  cron:
    name: "dump mongo"
    hour: "{{dump_time}}"
    job: "sh /usr/local/bin/dumpMongo.sh"
