---
- name: create first layer
  hosts: Guess_server
  become: yes
  roles:
    - role: base

- name: config collect dump
  hosts: save_server
  become: yes
  roles:
    - role: base
    - role: mongo
      version: 4.0.11
      dump_time: 1 #hours you want to dump
